Keycloak:
  Server: http://identity:8080
  Issuer: http://localhost:8992/realms/microservices-demo
  Authority: http://localhost:8992/realms/microservices-demo

ElasticApm:
  ServerUrl: http://apm-server:8200
  Environment: production

Logstash:
  Uri: http://logstash:28080
  Environment: production

OtelCollector:
  Endpoint: http://jaeger:4317

Eureka:
  Client:
    ServiceUrl: http://eureka.server:8761/eureka
