ElasticApm:
  ServerUrl: http://apm-server:8200
  Environment: production

Logstash:
  Uri: http://logstash:28080
  Environment: production

OtelCollector:
  Endpoint: http://jaeger:4317

ConnectionStrings:
  PricingConnection: "Host=postgres;Port=5432;Database=Microservices.Demo.Pricing;Username=postgres;Password=Password1234"

Eureka:
  Client:
    ServiceUrl: http://eureka.server:8761/eureka
