ElasticApm:
  ServerUrl: http://apm-server:8200
  Environment: production

Logstash:
  Uri: http://logstash:28080
  Environment: production

OtelCollector:
  Endpoint: http://jaeger:4317

Eureka:
  Client:
    ServiceUrl: http://eureka.server:8761/eureka

URLServices:
  Policies: http://products.service/api/policies
  Products: http://policies.service/api/products
